### ISSUE TITLE
Right solution to show missing followers?

### ISSUE THREAD

**Issue by drinkeboer** [TLDRMissions/TLDRMissions#514] opened 2022-08-02 09:06 UTC

**Comment by teelolws** [comment] 2022-08-02 09:09
Huh?

**Comment by drinkeboer** [comment] 2022-08-02 09:13
Sorry, pressed wrong button as you already found out.

**Comment by teelolws** [comment] 2022-08-02 09:14
Duplicate of https://github.com/TLDRMissions/TLDRMissions/issues/515

**Closed by teelolws** 2022-08-02 09:14 UTC
